### ISSUE TITLE
Multiple kinds don't supported

### ISSUE THREAD

**Issue by DarkHole1** [neverlane/shikimori#1]
According the [docs](https://shikimori.me/api/doc/1.0/animes/index) kinds can be a list. But `AnimeKinds` supporting only one possible value. There is workaround `kind: 'tv,ona' as AnimeKinds`, but it will be nicer have such feature in types.

P.S. Thanks for nice library :D

**Comment by neverlane** [comment]
sorry for the long answer, later I will add support for "subtraction values" (e.g. !tv) and an array of anime kinds(as well as for other types)

**Comment by neverlane** [comment]
fixed in 56e4ccae49f66179166b5333623a2d5a942273e4
